import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "@/styles/globals.css"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import ConnectDB from "../config/db"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Touch-Stack",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // await ConnectDB()
  return (
    <html lang="en">
      <body className="bg-[#E5E5E5] w-full h-screen">
        <main className=" bg-[#E5E5E5] px-3 py-8  max-w-[54rem] 3xl:max-w-[64rem] 4xl:max-w-[70rem]  m-auto  flex items-center justify-center md:justify-start  font-manrope">
          {children}
        </main>
        <ToastContainer />
      </body>
    </html>
  )
}
